version: '3'
services:
    exchange-api:
        build: 
            context: exchange-api
            dockerfile: Dockerfile
        image: elmma-exchange-api        
        volumes:
            - ./exchange-api:/usr/src/app
        ports:
            - "8080:8080"
        container_name: elmma-exchange-api
        networks:
            - elmma-nw
    elmma:
        build: 
            context: elmma
            dockerfile: Dockerfile
        image: elmma
        volumes:
            - ./elmma:/usr/src/app
            - ../.m2:/root/.m2
        ports:
            - "3000:8080"
        container_name: elmma
        networks:
            - elmma-nw     
        

networks:
    elmma-nw: