version: '3'
services:
    exchange-api:
        image: eimma-exchange-api
        volumes:
            - ./exchange-api:/usr/src/app
        ports:
            - "8080:8080"
        container_name: eimma-exchange-api
        networks:
            - adept-nw

networks:
    adept-nw: