version: '3'
services:
    exchange-api:
        image: elmma-exchange-api
        volumes:
            - ./exchange-api:/usr/src/app
        ports:
            - "8080:8080"
        container_name: elmma-exchange-api
        networks:
            - elmma-nw

networks:
    elmma-nw: