version: '3'
services:
    db:
        image: mysql:latest
        volumes:
            - ./mysql:/var/lib/mysql
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: elmma
            MYSQL_USER: elmma
            MYSQL_PASSWORD: 123456
        ports:
            - "3306:3306"
        container_name: elmma-db
        networks:
            - elmma-nw
            
    elmma:
        build: 
            context: elmma
            dockerfile: Dockerfile
        image: elmma
        volumes:
            - ./elmma:/usr/src/app
            - ../.m2:/root/.m2
        ports:
            - "3000:8080"
        container_name: elmma
        networks:
            - elmma-nw
        
networks:
    elmma-nw: