package de.elmma;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

import de.elmma.ElmmaHibernateConfiguration.HBM2DDL_AUTO;
import de.elmma.model.Company;
import de.elmma.model.Gender;
import de.elmma.model.Project;
import de.elmma.model.User;
import de.svenjacobs.loremipsum.LoremIpsum;

public class TestDataGenerator {
	private LoremIpsum l = new LoremIpsum();
	Random random = new Random(1);

	public static void main(String[] args) throws Exception {
		new TestDataGenerator();
	}

	public TestDataGenerator() throws Exception {
		SessionFactory sf = new ElmmaHibernateConfiguration(HBM2DDL_AUTO.CREATE).buildSessionFactory();
		Session session = sf.openSession();
		Transaction transaction = session.beginTransaction();

		for (int i = 0; i < projectNames.length; i++) {
			session.save(getProject(projectNames[i], i));
		}

		transaction.commit();
		session.close();
		sf.close();
	}

	private Project getProject(String projectName, int i) {
		Project project = new Project();
		project.setName(projectName);
		project.setDescription(l.getWords(50));
		project.setLogoUrl(logo[i % (logo.length - 1)]);
		project.getConsortium().addAll(getCompanies(5));
		return project;
	}

	private List<Company> getCompanies(int nr) {
		List<Company> l = new ArrayList<Company>();
		for (int i = 0; i < nr; i++) {
			l.add(companies.remove(random.nextInt(companies.size() - 1)));
		}
		l.forEach(e -> e.getAssociatedUsers().add(users.get(random.nextInt(users.size() - 1))));
		return l;
	}

	String[] logo = new String[] {
			"http://www.digitale-technologien.de/DT/Redaktion/EN/Bilder/Logos/excell-logo.png?__blob=normal&v=1",
			"http://www.digitale-technologien.de/DT/Redaktion/DE/Bilder/Logos/innoplan-logo.jpg?__blob=normal&v=1",
			"http://www.digitale-technologien.de/DT/Redaktion/DE/Bilder/Logos/itesa-logo.jpg?__blob=normal&v=2",
			"http://www.digitale-technologien.de/DT/Redaktion/DE/Bilder/Logos/kdi-logo.jpg?__blob=normal&v=1" };

	String[] projectNames = new String[] { "ExCELL", "InnOPlan", "iTESA", "KDI", "PRO-OPT", "SAHRA", "SAKE", "SD4M",
			"sd-kama", "SIDAP", "SmartDataWeb", "SmartEnergyHub", "SmartRegio", "VIRTUOSE-DE", "FAST GENOMICS", "EDV" };

	List<Company> companies = new ArrayList<Company>() {
		{
			addAll(Arrays.asList(new Company[] { new Company("11 88 0 SOLUTIONS AG", "Berlin", "Germany"),
					new Company("3U HOLDING AG", "Hamburg", "Germany"), new Company("4 SC AG", "München", "Germany"),
					new Company("A.S.CREATION TAPETEN NA", "Köln", "Germany"),
					new Company("A.SPRINGER SE VNA", "Frankfurt am Main", "Germany"),
					new Company("AAP IMPLANTATE AG", "Stuttgart", "Germany"),
					new Company("AAREAL BANK AG", "Düsseldorf", "Germany"),
					new Company("ACCENTRO R.EST.AG O.N.", "Dortmund", "Germany"),
					new Company("COMPUGROUP MED.AG O.N.", "Offenbach am Main", "Germany"),
					new Company("CONSTANTIN MEDIEN AG O.N.", "Ulm", "Germany"),
					new Company("CONTINENTAL AG O.N.", "Heilbronn", "Germany"),
					new Company("COVESTRO AG O.N.", "Pforzheim", "Germany"),
					new Company("C-QUADRAT INVESTM.AG EO 1", "Göttingen", "Germany"),
					new Company("CROPENERGIES AG", "Bottrop", "Germany"),
					new Company("CTS EVENTIM KGAA", "Trier", "Germany"),
					new Company("DAIMLER AG NA O.N.", "Recklinghausen", "Germany"),
					new Company("DATA MODUL AG O.N.", "Reutlingen", "Germany"),
					new Company("DEAG DT.ENTERTAINM..", "Bremer­haven", "Germany"),
					new Company("DELIVERY HERO AG", "Koblenz", "Germany"),
					new Company("DELTICOM AG", "Bergisch Gladbach", "Germany"),
					new Company("DEMIRE DT.MTS.RE AG", "Jena", "Germany"),
					new Company("DEUTSCHE BANK AG NA O.N.", "Remscheid", "Germany"),
					new Company("DEUTSCHE BOERSE NA O.N.", "Erlangen", "Germany"),
					new Company("DEUTSCHE EUROSHOP AG O.N.", "Moers", "Germany"),
					new Company("DEUTSCHE POST AG NA O.N.", "Siegen", "Germany"),
					new Company("DEUTSCHE WOHNEN AG", "Hildesheim", "Germany"),
					new Company("FRESEN.MED.CARE KGAA O.N.", "Erfurt", "Germany"),
					new Company("FRESENIUS SE+CO.KGAA O.N.", "Mainz", "Germany"),
					new Company("FUCHS PETROL.SE VZO O.N.", "Rostock", "Germany"),
					new Company("FUCHS PETROLUB SE O.N.", "Kassel", "Germany"),
					new Company("GEA GROUP AG", "Hagen", "Germany"), new Company("GERATHERM O.N.", "Hamm", "Germany"),
					new Company("GERRESHEIMER AG", "Saarbrücken", "Germany"),
					new Company("GERRY WEBER INTERNAT.O.N.", "Mülheim an der Ruhr", "Germany"),
					new Company("GESCO AG NA O.N.", "Potsdam", "Germany"),
					new Company("GFK SE O.N.", "Ludwigshafen am Rhein", "Germany"),
					new Company("GFT TECHNOLOGIES SE", "Oldenburg (Oldb)", "Germany"),
					new Company("GIGASET AG O.N.", "Leverkusen", "Germany"),
					new Company("GK SOFTWARE O.N.", "Osnabrück", "Germany"),
					new Company("GRAMMER AG O.N.", "Solingen", "Germany"),
					new Company("GRAND CITY PROPERTIES S.A.", "Heidelberg", "Germany"),
					new Company("GRENKELEASING AG O.N.", "Herne", "Germany"),
					new Company("H+R AG INH. O.N.", "Neuss", "Germany"),
					new Company("HAMBORNER REIT AG O.N.", "Darmstadt", "Germany"),
					new Company("HAMBURG.HAFEN U.LOG.A-SP", "Paderborn", "Germany"),
					new Company("HANN.RUECK SE NA O.N.", "Regensburg", "Germany"),
					new Company("HAPAG-LLOYD NA. O.N.", "Ingolstadt", "Germany"),
					new Company("HAWESKO HOLDING AG SVG", "Würzburg", "Germany"),
					new Company("HEIDELBERG.DRUCKMA.O.N.", "Fürth", "Germany"),
					new Company("HEIDELBERGCEMENT AG O.N.", "Wolfsburg", "Germany"),
					new Company("HELLA KGAA HUECK+CO. O.N.", "Offenbach am Main", "Germany"),
					new Company("HENKEL AG+CO.KGAA ST O.N.", "Ulm", "Germany"),
					new Company("HENKEL AG+CO.KGAA VZO", "Heilbronn", "Germany"),
					new Company("HIGHLIGHT CMNCTS INH.SF 1", "Pforzheim", "Germany"),
					new Company("HOCHTIEF AG", "Göttingen", "Germany"),
					new Company("HOLIDAYCHECK GROUP AG", "Bottrop", "Germany"),
					new Company("HORNBACH HOLD.ST O.N.", "Trier", "Germany"),
					new Company("HORNBACH-BAUMARKT O.N.", "Recklinghausen", "Germany"),
					new Company("HUGO BOSS AG NA O.N.", "Reutlingen", "Germany"),
					new Company("HYPOPORT AG", "Bremer­haven", "Germany"),
					new Company("INDUS HOLDING AG", "Koblenz", "Germany"),
					new Company("INFINEON TECH.AG NA O.N.", "Bergisch Gladbach", "Germany"),
					new Company("INIT INNOVATION O.N.", "Jena", "Germany"),
					new Company("INNOGY SE INH. O.N.", "Remscheid", "Germany"),
					new Company("INTERSHOP COMM.", "Erlangen", "Germany"),
					new Company("INTICA SYSTEMS AG", "Moers", "Germany"),
					new Company("INVISION AG", "Siegen", "Germany"),
					new Company("ISRA VISION O.N.", "Hildesheim", "Germany"),
					new Company("IVU TRAFFIC TECHN.AG O.N.", "Salzgitter ", "Germany"),
					new Company("JENOPTIK AG O.N.", "Berlin", "Germany"),
					new Company("JUNGHEINRICH AG O.N.VZO", "Hamburg", "Germany"),
					new Company("K+S AG NA O.N.", "München", "Germany"),
					new Company("KION GROUP AG", "Köln", "Germany"),
					new Company("KLOECKNER + CO SE NA", "Frankfurt am Main", "Germany"),
					new Company("KOENIG + BAUER AG ST O.N.", "Stuttgart", "Germany"),
					new Company("KONTRON AG O.N.", "Düsseldorf", "Germany"),
					new Company("KPS AG NA O.N.", "Dortmund", "Germany"),
					new Company("KROMI LOGISTIK INH. O.N.", "Essen", "Germany"),
					new Company("KRONES AG O.N.", "Leipzig", "Germany"), new Company("KUKA AG", "Bremen", "Germany"),
					new Company("KWS SAAT SE O.N.", "Dresden", "Germany"),
					new Company("LANXESS AG", "Hannover", "Germany"),
					new Company("LEG IMMOBILIEN AG", "Nürnberg", "Germany"),
					new Company("LEIFHEIT AG O.N.", "Duisburg", "Germany"),
					new Company("LEONI AG NA O.N.", "Bochum", "Germany"),
					new Company("LINDE AG O.N.", "Wuppertal", "Germany"),
					new Company("LOGWIN AG", "Bielefeld", "Germany"), new Company("LOTTO24 AG", "Bonn", "Germany"),
					new Company("LPKF LASER+ELECTRON.", "Münster", "Germany"),
					new Company("LUDW.BECK A.RATHAUSECK", "Karlsruhe", "Germany"),
					new Company("LUFTHANSA AG VNA O.N.", "Mannheim", "Germany"),
					new Company("M.A.X. AUTOMATION AG", "Augsburg", "Germany"),
					new Company("MANZ AG", "Wiesbaden", "Germany"),
					new Company("MASTERFLEX O.N.", "Gelsenkirchen", "Germany"),
					new Company("MBB SE O.N.", "Mönchen­gladbach, ", "Germany"),
					new Company("MEDICLIN AG", "Braunschweig", "Germany"),
					new Company("MEDIGENE NA O.N.", "Chemnitz", "Germany"),
					new Company("MERCK KGAA O.N.", "Kiel", "Germany"),
					new Company("METRO AG ST O.N.", "Aachen", "Germany"),
					new Company("METRO AG VZO O.N.", "Halle (Saale)10", "Germany"),
					new Company("MEVIS MEDICAL SOL.NA O.N.", "Magdeburg", "Germany"),
					new Company("MLP AG", "Freiburg im Breisgau", "Germany"),
					new Company("MOLOGEN AG", "Krefeld", "Germany"),
					new Company("MORPHOSYS AG O.N.", "Lübeck", "Germany"),
					new Company("MTU AERO ENGINES NA O.N.", "Oberhausen", "Germany"),
					new Company("MUENCH.RUECKVERS.VNA O.N.", "Erfurt", "Germany"),
					new Company("MVV ENERGIE AG O.N.", "Mainz", "Germany"),
					new Company("MYBET HOLDING SE NA O.N.", "Rostock", "Germany"),
					new Company("NEMETSCHEK AG O.N.", "Kassel", "Germany"),
					new Company("NEXUS AG O.N.", "Hagen", "Germany"), new Company("NORDEX SE O.N.", "Hamm", "Germany"),
					new Company("NORMA GROUP SE NA O.N.", "Saarbrücken", "Germany"),
					new Company("OHB AG O.N.", "Mülheim an der Ruhr", "Germany"),
					new Company("OSRAM LICHT AG NA O.N.", "Potsdam", "Germany"),
					new Company("OVB HOLDING AG", "Ludwigshafen am Rhein", "Germany"),
					new Company("PAION O.N", "Oldenburg (Oldb)", "Germany"),
					new Company("PARAGON AG", "Leverkusen", "Germany"),
					new Company("PATRIZIA IMMOBILIEN NA ON", "Osnabrück", "Germany"),
					new Company("PETRO WELT TECHNOLOGIE.AG", "Solingen", "Germany"),
					new Company("PFEIFFER VACUUM TECH.O.N.", "Heidelberg", "Germany"),
					new Company("PHOENIX SOLAR AG O.N.", "Herne", "Germany"),
					new Company("PNE WIND AG", "Neuss", "Germany"),
					new Company("PROCREDIT HLDG AG NA EO 5", "Darmstadt", "Germany"),
					new Company("PROGRESS-WERK OBERK. O.N.", "Paderborn", "Germany"),
					new Company("PROSIEBENSAT.1 O.N.VZO", "Regensburg", "Germany"),
					new Company("PSI SOFTWARE AG", "Ingolstadt", "Germany"),
					new Company("PUMA SE", "Würzburg", "Germany"), new Company("PVA TEPLA AG O.N.", "Fürth", "Germany"),
					new Company("QIAGEN NV EO -,01", "Wolfsburg", "Germany"),
					new Company("QSC AG NA O.N.", "Offenbach am Main", "Germany"),
					new Company("R. STAHL AG NA O.N.", "Ulm", "Germany"),
					new Company("RATIONAL AG", "Heilbronn", "Germany"),
					new Company("RHEINMETALL AG", "Pforzheim", "Germany"),
					new Company("RHOEN-KLINIKUM O.N.", "Göttingen", "Germany"),
					new Company("RIB SOFTWARE AG NA", "Bottrop", "Germany"),
					new Company("FYBER N.V.", "Trier", "Germany"),
					new Company("ROCKET INTERNET AG", "Recklinghausen", "Germany"),
					new Company("ROY CERAMICS SE", "Reutlingen", "Germany"),
					new Company("RTL GROUP", "Bremer­haven", "Germany"),
					new Company("RWE AG ST O.N.", "Koblenz", "Germany"),
					new Company("RWE AG VZO O.N.", "Bergisch Gladbach", "Germany"),
					new Company("S+T AG (Z.REG.MK.Z.)O.N.", "Jena", "Germany"),
					new Company("SAF HOLLAND S.A. EO-,01", "Remscheid", "Germany"),
					new Company("SALZGITTER AG O.N.", "Erlangen", "Germany"),
					new Company("SAP SE O.N.", "Moers", "Germany"),
					new Company("SLM SOLUTIONS GRP AG", "Wuppertal", "Germany"),
					new Company("SMA SOLAR TECHNOL.AG", "Bielefeld", "Germany"),
					new Company("SMT SCHARF AG", "Bonn", "Germany"), new Company("SNOWBIRD AG", "Münster", "Germany"),
					new Company("SNP SCHNEID.-NEUREIT.O.N.", "Karlsruhe", "Germany"),
					new Company("SOFTING AG O.N.", "Mannheim", "Germany"),
					new Company("SOFTWARE AG O.N.", "Augsburg", "Germany"),
					new Company("SOLARWORLD AG O.N.", "Wiesbaden", "Germany"),
					new Company("STABILUS S.A. INH. EO-,01", "Gelsenkirchen", "Germany"),
					new Company("STADA ARZNEIMITT.VNA O.N.", "Mönchen­gladbach, ", "Germany"),
					new Company("STEINHOFF INT.HLDG.EO-,50", "Braunschweig", "Germany"),
					new Company("STRATEC BIOMEDICAL NAM.ON", "Chemnitz", "Germany"),
					new Company("STROEER SE", "Kiel", "Germany"),
					new Company("SUEDZUCKER AG O.N.", "Aachen", "Germany"),
					new Company("SUESS MICROTEC NA O.N.", "Halle (Saale)11", "Germany"),
					new Company("SURTECO SE", "Magdeburg", "Germany"),
					new Company("SYGNIS AG", "Freiburg im Breisgau", "Germany"),
					new Company("SYMRISE AG INH. O.N.", "Krefeld", "Germany"),
					new Company("SYZYGY AG O.N.", "Lübeck", "Germany"),
					new Company("TAG IMMOBILIEN AG", "Oberhausen", "Germany"),
					new Company("TAKKT AG O.N.", "Erfurt", "Germany"),
					new Company("TALANX AG NA O.N.", "Mainz", "Germany"),
					new Company("TECHNOTRANS AG NA O.N.", "Rostock", "Germany"),
					new Company("TELE COLUMBUS AG", "Kassel", "Germany"),
					new Company("TELEFONICA DTLD HLDG AG", "Hagen", "Germany"),
					new Company("TELES AG INFORM.TECHN.", "Hamm", "Germany"),
					new Company("THYSSENKRUPP AG O.N.", "Saarbrücken", "Germany"),
					new Company("TLG IMMOBILIEN AG", "Mülheim an der Ruhr", "Germany"),
					new Company("TOM TAILOR HOLDING SE", "Potsdam", "Germany"),
					new Company("UMS I.L. O.N.", "Ludwigshafen am Rhein", "Germany"),
					new Company("UNIPER SE NA.", "Oldenburg (Oldb)", "Germany"),
					new Company("UNITED LABELS O.N.", "Leverkusen", "Germany"),
					new Company("USU SOFTWARE AG", "Osnabrück", "Germany"),
					new Company("UTD.INTERNET AG NA", "Solingen", "Germany"),
					new Company("VAPIANO SE", "Heidelberg", "Germany"), new Company("VA-Q-TEC AG", "Herne", "Germany"),
					new Company("VERBIO VER.BIOENERGIE ON", "Neuss", "Germany"),
					new Company("VILLEROY + BOCH AG VZ", "Darmstadt", "Germany"),
					new Company("VISCOM AG O.N.", "Paderborn", "Germany"),
					new Company("VITA 34 AG", "Regensburg", "Germany"),
					new Company("VOLKSWAGEN AG ST O.N.", "Ingolstadt", "Germany"),
					new Company("VOLKSWAGEN AG VZO O.N.", "Würzburg", "Germany"),
					new Company("VONOVIA SE NA O.N.", "Fürth", "Germany"),
					new Company("VOSSLOH AG O.N.", "Wolfsburg", "Germany"),
					new Company("VTG AG O.N.", "Offenbach am Main", "Germany"),
					new Company("WACKER CHEMIE O.N.", "Ulm", "Germany"),
					new Company("WACKER NEUSON NA O.N.", "Heilbronn", "Germany"),
					new Company("WASHTEC AG O.N.", "Pforzheim", "Germany"),
					new Company("WCM BET.GRD.AG O.N.", "Göttingen", "Germany"),
					new Company("WESTAG + GETALIT ST O.N.", "Bottrop", "Germany"),
					new Company("WESTAG + GETALIT VZO O.N.", "Trier", "Germany"),
					new Company("WILEX AG O.N.", "Recklinghausen", "Germany"),
					new Company("WINDELN.DE AG O.N.", "Reutlingen", "Germany"),
					new Company("WIRECARD AG", "Bremer­haven", "Germany"),
					new Company("WUESTENROT+WUERTT.AG O.N.", "Koblenz", "Germany"),
					new Company("XING AG", "Bergisch Gladbach", "Germany"),
					new Company("YOC AG O.N.", "Jena", "Germany"), new Company("ZALANDO SE", "Remscheid", "Germany"),
					new Company("ZEAL Network SE", "Erlangen", "Germany"),
					new Company("ZHONGDE WASTE TECHNOLOGY", "Moers", "Germany"),
					new Company("ZOOPLUS AG", "Siegen", "Germany"),
					new Company("3W POWER S.A.", "Hildesheim", "Germany"),
					new Company("7C SOLARPARKEN AG O.N.", "Salzgitter ", "Germany"),
					new Company("A.A.A.AG ALLG.ANL.VERW", "Berlin", "Germany"),
					new Company("A.I.S. AG", "Hamburg", "Germany"),
					new Company("ABWICKLUNGSG. ROESCH O.N.", "München", "Germany"),
					new Company("ADESSO AG O.N.", "Köln", "Germany"),
					new Company("AGENNIX AG I.A.", "Frankfurt am Main", "Germany"),
					new Company("ALBA SE O.N.", "Stuttgart", "Germany"),
					new Company("ALBIS LEASING AG O.N.", "Düsseldorf", "Germany"),
					new Company("ALLGEIER SE O.N.", "Dortmund", "Germany"), new Company("ALNO AG", "Essen", "Germany"),
					new Company("AMATECH AG O.N.", "Leipzig", "Germany"),
					new Company("ARCANDOR AG O.N.", "Bremen", "Germany"),
					new Company("ASIAN BAMBOO AG INH.ON", "Dresden", "Germany"),
					new Company("AUDI AG O.N.", "Hannover", "Germany"),
					new Company("B+S BANKSYSTEME AG O.N.", "Nürnberg", "Germany"),
					new Company("BABCOCK-BSH AG O.N.", "Duisburg", "Germany"),
					new Company("BBS KRAFTFAHR.TEC.VZO O.N", "Bochum", "Germany"),
					new Company("BEATE UHSE AG", "Wuppertal", "Germany"),
					new Company("BERENTZEN-GRP.AG", "Bielefeld", "Germany"),
					new Company("BHS TABLETOP AG O.N.", "Bonn", "Germany"),
					new Company("BIJOU BRIGITTE O.N.", "Münster", "Germany"),
					new Company("BOEWE SYSTEC AG O.N.", "Karlsruhe", "Germany"),
					new Company("CHINA SPEC.GLASS AG", "Mannheim", "Germany"),
					new Company("CHORUS CLEAN ENERGY AG", "Augsburg", "Germany"),
					new Company("CIECH S.A. ZY 5", "Wiesbaden", "Germany"),
					new Company("CO.DON AG O.N. .", "Gelsenkirchen", "Germany"),
					new Company("CPI PROPERTY GRP", "Mönchen­gladbach, ", "Germany"),
					new Company("CURASAN AG", "Braunschweig", "Germany"),
					new Company("DECHENG TECHNOLOGY AG", "Chemnitz", "Germany"),
					new Company("DF DT.FORFAIT AG", "Kiel", "Germany"),
					new Company("DIERIG HOLDING AG O.N.", "Aachen", "Germany"),
					new Company("DT.CANNABIS AG O.N.", "Halle (Saale)12", "Germany"),
					new Company("DT.REAL ESTATE AG O.N.", "Magdeburg", "Germany"),
					new Company("DUERKOPP ADLER AG O.N.", "Freiburg im Breisgau", "Germany"),
					new Company("DVB BANK SE O.N.", "Krefeld", "Germany"),
					new Company("EASY SOFTWARE AG", "Lübeck", "Germany"),
					new Company("EISEN- U.HUETTENWERKE", "Oberhausen", "Germany"),
					new Company("ELANIX BIOTECHN.AG", "Erfurt", "Germany"),
					new Company("ELECTRAWINDS SE A", "Mainz", "Germany"),
					new Company("GELSENWASSER AG", "Herne", "Germany"),
					new Company("GSW IMMOBILIEN AG", "Neuss", "Germany"),
					new Company("GWB IMMOBILIEN INH. O.N.", "Darmstadt", "Germany"),
					new Company("HANSEYACHTS O.N.", "Paderborn", "Germany"),
					new Company("HEIDEL.BETEIL.HLDG AG", "Regensburg", "Germany"),
					new Company("HELIOCENTRIS EN.SOL.AG NA", "Ingolstadt", "Germany"),
					new Company("HESSE NEWMAN CAP.AG", "Würzburg", "Germany"),
					new Company("IFA HOTEL U.TOURISTI.O.N.", "Fürth", "Germany"),
					new Company("INFAS HLDG AG O.N.", "Wolfsburg", "Germany"),
					new Company("INTERTAINMENT O.N.", "Offenbach am Main", "Germany"),
					new Company("ITN NANOVATION", "Ulm", "Germany"),
					new Company("JJ AUTO AG O.N.", "Heilbronn", "Germany"),
					new Company("JUBII EUROPE N.V.B EO-,01", "Pforzheim", "Germany"),
					new Company("KAMPA AG O.N.", "Göttingen", "Germany"),
					new Company("KAP-BETEILIGUNGS-AG O.N.", "Bottrop", "Germany"),
					new Company("KHD HUMB.WEDAG IND. NA", "Trier", "Germany"),
					new Company("KHD HUMBOLDT WEDAG O.N.", "Recklinghausen", "Germany"),
					new Company("KLASSIK RADIO AG NA O.N.", "Reutlingen", "Germany"),
					new Company("KSB AG O.N. ST", "Bremer­haven", "Germany"),
					new Company("KSB AG O.N. VZO", "Koblenz", "Germany"),
					new Company("LS TELCOM AG", "Bergisch Gladbach", "Germany"),
					new Company("M+S ELEKTRONIK AG", "Jena", "Germany"),
					new Company("MAIER + PARTNER O.N.", "Remscheid", "Germany"),
					new Company("MAINOVA AG O.N.", "Erlangen", "Germany"),
					new Company("MYPHOTOALBUM INC. 144A", "Bremen", "Germany"),
					new Company("NESCHEN AG O.N.", "Dresden", "Germany"),
					new Company("NORCOM INF.TECHN.AG", "Hannover", "Germany"),
					new Company("NORDWEST HANDEL AG", "Nürnberg", "Germany"),
					new Company("OASMIA PHARMACEUT. SK-,10", "Duisburg", "Germany"),
					new Company("ODEON FILM AG O.N.", "Bochum", "Germany"),
					new Company("OMRON CORP. DZ/1 O.N.", "Wuppertal", "Germany"),
					new Company("OPENLIMIT HLDG INH. SF-30", "Bielefeld", "Germany"),
					new Company("ORBIS AG O.N.", "Bonn", "Germany"), new Company("PANAMAX AG", "Münster", "Germany"),
					new Company("PEARL GOLD AG", "Karlsruhe", "Germany"),
					new Company("PELIKAN AG O.N.", "Mannheim", "Germany"),
					new Company("PFERDEWETTEN.DE AG", "Augsburg", "Germany"),
					new Company("PHILIPP HOLZMANN AG O.N.", "Wiesbaden", "Germany"),
					new Company("PITTLER MA.FABR. AG", "Gelsenkirchen", "Germany"),
					new Company("PONGS + ZAHN AG O.N.", "Mönchen­gladbach, ", "Germany"),
					new Company("PORSCHE AUTOM.HLDG VZO", "Braunschweig", "Germany"),
					new Company("REALTECH AG O.N.", "Chemnitz", "Germany"),
					new Company("S+O AGRAR AG O.N.", "Kiel", "Germany"),
					new Company("SCHLOSS WACHENHEIM AG O.N", "Aachen", "Germany"),
					new Company("SCHUMAG AG O.N.", "Halle (Saale)13", "Germany"),
					new Company("SCHWEIZER ELECTR. NA O.N.", "Magdeburg", "Germany"),
					new Company("SIMONA AG O.N.", "Freiburg im Breisgau", "Germany"),
					new Company("SINNER AG O.N.", "Krefeld", "Germany"),
					new Company("SINO-GERMAN UTD AG O.N.", "Lübeck", "Germany"),
					new Company("SOFTMATIC AG O.N.", "Oberhausen", "Germany"),
					new Company("SOLAR-FABRIK AG O.N.", "Erfurt", "Germany"),
					new Company("SPL.MEDIEN AG O.N.", "Mainz", "Germany"),
					new Company("SPOBAG O.N.", "Rostock", "Germany"),
					new Company("STARAMBA SE O.N.", "Kassel", "Germany"),
					new Company("STEILMANN SE", "Hagen", "Germany"),
					new Company("STO SE+CO.KGAA VZO O.N.", "Hamm", "Germany"),
					new Company("STOCKHOLM IT VENTURES AB", "Saarbrücken", "Germany"),
					new Company("STRABAG AG NA", "Mülheim an der Ruhr", "Germany"),
					new Company("TC UNTERHALTUNGSELEK.", "Potsdam", "Germany"),
					new Company("TDMI AG O.N.", "Ludwigshafen am Rhein", "Germany"),
					new Company("TISCON AG O.N.", "Oldenburg (Oldb)", "Germany"),
					new Company("TMC CONTENT GR.AG INH.SF1", "Leverkusen", "Germany"),
					new Company("TRAVEL24.COM AG", "Osnabrück", "Germany"),
					new Company("TTL INF. TECHN. AG O.N.", "Solingen", "Germany"),
					new Company("TURBON AG O.N.", "Heidelberg", "Germany"),
					new Company("ULTRASONIC AG O.N.", "Herne", "Germany"), new Company("UNICREDIT", "Neuss", "Germany"),
					new Company("UNIPROF REAL HLD O.N.", "Darmstadt", "Germany"),
					new Company("UTD POWER TECHN.AG", "Paderborn", "Germany"),
					new Company("UZIN UTZ AG O.N.", "Regensburg", "Germany"),
					new Company("VALUE MANAGEM.+RES..", "Ingolstadt", "Germany"),
					new Company("VDN AG O.N.", "Würzburg", "Germany"),
					new Company("VERALLIA DTLD AG O.N.", "Fürth", "Germany"),
					new Company("VIVANCO GRUPPE AG", "Wolfsburg", "Germany"),
					new Company("VTION WIRELESS TECH. AG", "Offenbach am Main", "Germany"),
					new Company("WALTER BAU-AG ST O.N.", "Ulm", "Germany"),
					new Company("WALTER BAU-AG VZO O.N.", "Heilbronn", "Germany"),
					new Company("WANDERER-WERKE AKTIEN", "Pforzheim", "Germany"),
					new Company("WASGAU PROD.HANDELS AG", "Göttingen", "Germany"),
					new Company("WEBAC HOLDING AG", "Bottrop", "Germany"),
					new Company("WIGE MEDIA AG", "Trier", "Germany"),
					new Company("WILD BUNCH AG O.N.", "Recklinghausen", "Germany"),
					new Company("WIZCOM TECHS IS-,01", "Reutlingen", "Germany"),
					new Company("YMOS AG O.N.", "Bremer­haven", "Germany"),
					new Company("YOUBISHENG GR.PAPER AG", "Koblenz", "Germany"),
					new Company("YOUR FAMILY ENTER.AG NA", "Bergisch Gladbach", "Germany") }));
		}
	};

	List<User> users = new ArrayList<User>() {
		{
			addAll(Arrays.asList(new User[] { new User(Gender.MALE, "Kyoko", "Asaro", "Kyoko.Asaro@domain.de"),
					new User(Gender.MALE, "Melida", "Riney", "Melida.Riney@domain.de"),
					new User(Gender.MALE, "Ada", "Raby", "Ada.Raby@domain.de"),
					new User(Gender.MALE, "Emeline", "Armstong", "Emeline.Armstong@domain.de"),
					new User(Gender.MALE, "Inge", "Stickley", "Inge.Stickley@domain.de"),
					new User(Gender.MALE, "Todd", "Basta", "Todd.Basta@domain.de"),
					new User(Gender.MALE, "Fe", "Pleas", "Fe.Pleas@domain.de"),
					new User(Gender.FEMALE, "Meridith", "Balsley", "Meridith.Balsley@domain.de"),
					new User(Gender.FEMALE, "Herta", "Hanner", "Herta.Hanner@domain.de"),
					new User(Gender.FEMALE, "Mendy", "Hoeft", "Mendy.Hoeft@domain.de"),
					new User(Gender.FEMALE, "Latrisha", "Siems", "Latrisha.Siems@domain.de"),
					new User(Gender.MALE, "Jackie", "Fultz", "Jackie.Fultz@domain.de"),
					new User(Gender.FEMALE, "Alycia", "Portales", "Alycia.Portales@domain.de"),
					new User(Gender.MALE, "Kellye", "Hauck", "Kellye.Hauck@domain.de"),
					new User(Gender.MALE, "Lynn", "Feliz", "Lynn.Feliz@domain.de"),
					new User(Gender.MALE, "Vivienne", "Carrol", "Vivienne.Carrol@domain.de"),
					new User(Gender.FEMALE, "Tracey", "Nokes", "Tracey.Nokes@domain.de"),
					new User(Gender.MALE, "Honey", "Greenblatt", "Honey.Greenblatt@domain.de"),
					new User(Gender.FEMALE, "Broderick", "Anzaldua", "Broderick.Anzaldua@domain.de"),
					new User(Gender.MALE, "Robert", "Thies", "Robert.Thies@domain.de"),
					new User(Gender.FEMALE, "Henrietta", "Diblasi", "Henrietta.Diblasi@domain.de"),
					new User(Gender.FEMALE, "Jeanetta", "Abalos", "Jeanetta.Abalos@domain.de"),
					new User(Gender.FEMALE, "Hai", "Tovar", "Hai.Tovar@domain.de"),
					new User(Gender.MALE, "Riva", "Heimbach", "Riva.Heimbach@domain.de"),
					new User(Gender.MALE, "Cathi", "Wison", "Cathi.Wison@domain.de"),
					new User(Gender.MALE, "Soraya", "Gilkison", "Soraya.Gilkison@domain.de"),
					new User(Gender.MALE, "Nada", "Doolin", "Nada.Doolin@domain.de"),
					new User(Gender.FEMALE, "Glenna", "Hepfer", "Glenna.Hepfer@domain.de"),
					new User(Gender.MALE, "Rhoda", "Raabe", "Rhoda.Raabe@domain.de"),
					new User(Gender.FEMALE, "Lidia", "Valliere", "Lidia.Valliere@domain.de"),
					new User(Gender.FEMALE, "Rubin", "Burchfield", "Rubin.Burchfield@domain.de"),
					new User(Gender.FEMALE, "Refugio", "Oesterling", "Refugio.Oesterling@domain.de"),
					new User(Gender.FEMALE, "Muriel", "Fickel", "Muriel.Fickel@domain.de"),
					new User(Gender.FEMALE, "Lucille", "Tiller", "Lucille.Tiller@domain.de"),
					new User(Gender.FEMALE, "Jennine", "Poff", "Jennine.Poff@domain.de"),
					new User(Gender.MALE, "Allegra", "Eichelberger", "Allegra.Eichelberger@domain.de"),
					new User(Gender.MALE, "Gwendolyn", "Westover", "Gwendolyn.Westover@domain.de"),
					new User(Gender.FEMALE, "Shayna", "Abdulla", "Shayna.Abdulla@domain.de"),
					new User(Gender.FEMALE, "Tamala", "Rosenbalm", "Tamala.Rosenbalm@domain.de"),
					new User(Gender.FEMALE, "Latosha", "Prout", "Latosha.Prout@domain.de"),
					new User(Gender.MALE, "Michal", "Frasher", "Michal.Frasher@domain.de"),
					new User(Gender.MALE, "Sherman", "Carley", "Sherman.Carley@domain.de"),
					new User(Gender.MALE, "Earlene", "Conine", "Earlene.Conine@domain.de"),
					new User(Gender.FEMALE, "Nicolette", "Emig", "Nicolette.Emig@domain.de"),
					new User(Gender.MALE, "Lashaun", "Brummitt", "Lashaun.Brummitt@domain.de"),
					new User(Gender.MALE, "Jadwiga", "Merle", "Jadwiga.Merle@domain.de"),
					new User(Gender.FEMALE, "Ema", "Plumlee", "Ema.Plumlee@domain.de"),
					new User(Gender.FEMALE, "Reagan", "Sattler", "Reagan.Sattler@domain.de"),
					new User(Gender.MALE, "Abram", "Ranson", "Abram.Ranson@domain.de") }));
		}
	};
}
